name: llmroost
agg_type: sum
batch_size: 1024
input_size: 200
in_channels: 64
n_graphs: 3
elem_heads: 3 
internal_elem_dim: ${model.in_channels}
g_elem_dim: 256 
f_elem_dim: 256 
comp_heads: 4 
g_comp_dim: 256 
f_comp_dim: 256 
negative_slope: 0.2

encoder:
  _target_: assets.roost_encoder.RoostEncoder
  internal_elem_dim: ${model.internal_elem_dim}
  input_dim: ${model.in_channels}
  n_graphs: ${model.n_graphs}
  elem_heads: ${model.elem_heads}
  g_elem_dim: ${model.g_elem_dim}
  f_elem_dim: ${model.f_elem_dim}
  comp_heads: ${model.comp_heads}
  g_comp_dim: ${model.g_comp_dim}
  f_comp_dim: ${model.f_comp_dim}
  bias: false
  negative_slope: ${model.negative_slope}

resnet:
  _target_: assets.down_nn.ResidualNetwork
  internal_elem_dim: ${model.internal_elem_dim}
  output_dim: 1
  hidden_layer_dims:
    - 512
    - 256
    - 128
    - 64
  batchnorm: false

defaults:
  - llm: matscibert
