# reproducibility
deterministic: true
random_state: ${random_state}

# training
pl_trainer:
  fast_dev_run: false # Enable this for debug purposes
  gpus: 1
  precision: 32
  max_epochs: 300
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value

monitor_metric: 'val_loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: 40
  verbose: False

model_checkpoints:
  save_top_k: 1
  verbose: False